### PR TITLE
Cross-correlation function analysis tool

### PR DESCRIPTION
**Pull request by kgullikson88**
This is a dashboard I developed to help me interact with the data for my PhD thesis in astronomy. It demonstrates how to interface with an HDF5 file through bokeh-server.

### CODE REVIEW

**Comment by fpliger** [comment]
thanks @kgullikson88 !! Is it ready for review?

**Comment by bryevdv** [comment]
Just an FYI in the future we might try to stand up a Blaze server to support data URLs for thee demos, but the fetch data script is perfect for now.

**Comment by kgullikson88** [comment]
@fpliger yeah I think it is ready for review now. 

The data is stored on my astronomy website right now, but that will disappear at some point after I graduate so might not be the best long-term solution.

**Comment by bryevdv** [comment]
We could move it to our S3 bucket for `bokeh.sampledata` if we need to at some point.

**Comment by bryevdv** [comment]
Closing, this repo will be deleted soon

**Pull request closed without merging**
