### PR TITLE
EP 2015 airports demo

### PR DESCRIPTION
**Pull request by fpliger**

### CODE REVIEW

**Comment by damianavila** [comment]
@fpliger can you add a README to know how to start to trying this? I can look into the code but from the user perspective we need something to introduce the example (and also save me some time in the review :stuck_out_tongue:)

**Comment by fpliger** [comment]
@damianavila yes.. it is in WIP status. I just wanted to start a PR with what I have for now (the 1st goal was my EuroPython talk). I have some notes that I'm going to dump into a README and the plan is to then use this demo as base for a series of blog posts..

**Comment by fpliger** [comment]
@damianavila done. It should be ready for review :wink: 
Thanks!

**Comment by fpliger** [comment]
It's not working on py3... will fix it asap

@bryevdv FYI, you may want to wait for the fix before reviewing

**Comment by bryevdv** [comment]
Ok! thanks @fpliger

**Comment by bryevdv** [comment]
I get errors running the dashboard (even with py2). One thing that would improve the animated example would be to highlight the "central" city, and if possible highlight the next upcoming central city. That especially would give the user's attention a place to focus and where to expect the next thing to happen.

**Comment by fpliger** [comment]
@bryevdv , would you be able to send be the traceback you’re getting running the airports_dashboard demo with py2? wasn't able to reproduce..

Thanks for the improvements suggestions, nice ones ;-)

**Comment by bryevdv** [comment]
Turns out I was testing with bokeh 0.9.0 in my 2.7 env. Works fine on master.

**Comment by fpliger** [comment]
Cool.. Will leave it as WIP for a bit while I add improvements and fix compatibility with py3. Thanks!

**Comment by bryevdv** [comment]
Closing, this repo will be deleted soon

**Pull request closed without merging**
